const ISNEEDINIT = 'ISNEEDINIT';
const NONEEDINIT = 'NONEEDINIT';
const GETSCENIC = 'GETSCENIC';
const GETSCENICPREV ='GETSCENICPREV';
const SEARCHNAME ='SEARCHNAME';
const TOPAGE ='TOPAGE';
const ISLOADING='ISLOADING'
const NOLOADING='NOLOADING'
const ISSEARCH='ISSEARCH'
const NOSEARCH='NOSEARCH'
const ISGETPREV='ISGETPREV'
const NOGETPREV='NOGETPREV'
const ISNEXTPAGE='ISNEXTPAGE'
const NONEXTPAGE='NONEXTPAGE'
const GETINITSCENIC='GETINITSCENIC'
const SETSCROLLTOP='SETSCROLLTOP'

export { ISNEEDINIT, NONEEDINIT, GETSCENIC, GETSCENICPREV, SEARCHNAME, TOPAGE, ISLOADING, NOLOADING, GETINITSCENIC, ISSEARCH, NOSEARCH, ISGETPREV, NOGETPREV, ISNEXTPAGE, NONEXTPAGE, SETSCROLLTOP};